-- Runtime migration 0023_job_cost_evidence_foundation is the deployable source
-- of truth. This checked-in Drizzle artifact mirrors its durable data model.
CREATE TABLE IF NOT EXISTS "material_library" (
  "id" serial PRIMARY KEY, "company_id" integer NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE, "owner_user_id" text NOT NULL,
  "name" text NOT NULL, "category" text, "supplier_name" text, "supplier_sku" text, "unit" text, "attributes" jsonb,
  "active" boolean NOT NULL DEFAULT true, "latest_confirmed_unit_cost" numeric(14,4), "latest_confirmed_total_cost" numeric(14,2),
  "latest_confirmed_at" timestamptz, "latest_source_type" text, "latest_source_document_id" integer,
  "latest_source_receipt_id" integer REFERENCES "finance_receipts"("id") ON DELETE SET NULL, "latest_source_expense_id" integer REFERENCES "finance_expenses"("id") ON DELETE SET NULL,
  "created_by_user_id" text NOT NULL, "updated_by_user_id" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "material_cost_history" (
  "id" serial PRIMARY KEY, "material_id" integer NOT NULL REFERENCES "material_library"("id") ON DELETE CASCADE, "company_id" integer NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE, "owner_user_id" text NOT NULL,
  "unit_cost" numeric(14,4) NOT NULL CHECK ("unit_cost" >= 0), "total_cost" numeric(14,2) CHECK ("total_cost" >= 0), "quantity" numeric(14,3) CHECK ("quantity" >= 0), "unit" text, "supplier_name" text, "source_type" text NOT NULL,
  "source_document_id" integer, "source_receipt_id" integer REFERENCES "finance_receipts"("id") ON DELETE SET NULL, "source_expense_id" integer REFERENCES "finance_expenses"("id") ON DELETE SET NULL,
  "extraction_method" text, "confidence_score" numeric(4,3), "confirmed_by_user_id" text NOT NULL, "confirmed_at" timestamptz NOT NULL DEFAULT now(), "created_at" timestamptz NOT NULL DEFAULT now()
);
-- Evidence tables have the common tenant/provenance/confirmation columns from runtime 0023.
CREATE TABLE IF NOT EXISTS "job_labour_entries" ("id" serial PRIMARY KEY, "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE, "company_id" integer NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE, "owner_user_id" text NOT NULL, "work_date" date, "person_name" text, "person_reference" text, "entry_type" text, "estimated_hours" numeric(12,2) CHECK ("estimated_hours">=0), "actual_hours" numeric(12,2) CHECK ("actual_hours">=0), "hourly_cost" numeric(14,4) CHECK ("hourly_cost">=0), "estimated_cost" numeric(14,2) CHECK ("estimated_cost">=0), "actual_cost" numeric(14,2) CHECK ("actual_cost">=0), "notes" text, "source_type" text NOT NULL DEFAULT 'manual', "source_document_id" integer, "source_receipt_id" integer REFERENCES "finance_receipts"("id") ON DELETE SET NULL, "source_expense_id" integer REFERENCES "finance_expenses"("id") ON DELETE SET NULL, "extraction_method" text, "confidence_score" numeric(4,3), "confirmation_state" text NOT NULL DEFAULT 'confirmed', "confirmed_by_user_id" text, "confirmed_at" timestamptz, "created_by_user_id" text NOT NULL, "updated_by_user_id" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "job_material_usages" (
 "id" serial PRIMARY KEY, "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE, "company_id" integer NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE, "owner_user_id" text NOT NULL, "material_id" integer REFERENCES "material_library"("id") ON DELETE SET NULL, "name" text NOT NULL, "supplier_name" text, "supplier_sku" text, "unit" text, "specification" text, "attributes" jsonb, "estimated_quantity" numeric(14,3) CHECK ("estimated_quantity">=0), "actual_quantity" numeric(14,3) CHECK ("actual_quantity">=0), "waste_quantity" numeric(14,3) CHECK ("waste_quantity">=0), "waste_percent" numeric(7,3) CHECK ("waste_percent">=0), "estimated_unit_cost" numeric(14,4) CHECK ("estimated_unit_cost">=0), "actual_unit_cost" numeric(14,4) CHECK ("actual_unit_cost">=0), "estimated_cost" numeric(14,2) CHECK ("estimated_cost">=0), "actual_cost" numeric(14,2) CHECK ("actual_cost">=0), "notes" text, "source_type" text NOT NULL DEFAULT 'manual', "source_document_id" integer, "source_receipt_id" integer REFERENCES "finance_receipts"("id") ON DELETE SET NULL, "source_expense_id" integer REFERENCES "finance_expenses"("id") ON DELETE SET NULL, "extraction_method" text, "confidence_score" numeric(4,3), "confirmation_state" text NOT NULL DEFAULT 'confirmed', "confirmed_by_user_id" text, "confirmed_at" timestamptz, "created_by_user_id" text NOT NULL, "updated_by_user_id" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "job_other_direct_costs" (
 "id" serial PRIMARY KEY, "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE, "company_id" integer NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE, "owner_user_id" text NOT NULL, "description" text NOT NULL, "category" text, "estimated_cost" numeric(14,2) CHECK ("estimated_cost">=0), "actual_cost" numeric(14,2) CHECK ("actual_cost">=0), "notes" text, "source_type" text NOT NULL DEFAULT 'manual', "source_document_id" integer, "source_receipt_id" integer REFERENCES "finance_receipts"("id") ON DELETE SET NULL, "source_expense_id" integer REFERENCES "finance_expenses"("id") ON DELETE SET NULL, "extraction_method" text, "confidence_score" numeric(4,3), "confirmation_state" text NOT NULL DEFAULT 'confirmed', "confirmed_by_user_id" text, "confirmed_at" timestamptz, "created_by_user_id" text NOT NULL, "updated_by_user_id" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "job_finance_allocations" ("id" serial PRIMARY KEY, "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE, "company_id" integer NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE, "owner_user_id" text NOT NULL, "receipt_id" integer REFERENCES "finance_receipts"("id") ON DELETE CASCADE, "expense_id" integer REFERENCES "finance_expenses"("id") ON DELETE CASCADE, "receipt_line_reference" text, "allocated_amount" numeric(14,2) NOT NULL CHECK ("allocated_amount">=0), "allocated_quantity" numeric(14,3) CHECK ("allocated_quantity">=0), "unit" text, "notes" text, "confirmation_state" text NOT NULL DEFAULT 'confirmed', "confirmed_by_user_id" text, "confirmed_at" timestamptz, "created_by_user_id" text NOT NULL, "updated_by_user_id" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CHECK ("receipt_id" IS NOT NULL OR "expense_id" IS NOT NULL));
ALTER TABLE "job_intelligence_components" ADD COLUMN IF NOT EXISTS "unit" text, ADD COLUMN IF NOT EXISTS "specification" text, ADD COLUMN IF NOT EXISTS "attributes" jsonb, ADD COLUMN IF NOT EXISTS "estimated_quantity" numeric(10,3), ADD COLUMN IF NOT EXISTS "actual_quantity" numeric(10,3), ADD COLUMN IF NOT EXISTS "estimated_cost" numeric(10,2), ADD COLUMN IF NOT EXISTS "actual_cost" numeric(10,2), ADD COLUMN IF NOT EXISTS "waste_quantity" numeric(10,3), ADD COLUMN IF NOT EXISTS "waste_percent" numeric(7,3);
CREATE INDEX IF NOT EXISTS "material_library_tenant_search_idx" ON "material_library" ("company_id","owner_user_id","active","name");
CREATE INDEX IF NOT EXISTS "material_cost_history_material_confirmed_idx" ON "material_cost_history" ("material_id","confirmed_at" DESC);
CREATE INDEX IF NOT EXISTS "job_labour_entries_job_idx" ON "job_labour_entries" ("job_id","created_at");
CREATE INDEX IF NOT EXISTS "job_material_usages_job_idx" ON "job_material_usages" ("job_id","created_at");
CREATE INDEX IF NOT EXISTS "job_other_direct_costs_job_idx" ON "job_other_direct_costs" ("job_id","created_at");
CREATE INDEX IF NOT EXISTS "job_finance_allocations_job_idx" ON "job_finance_allocations" ("job_id","created_at");