/**
 * PWA update prompt.
 *
 * When Workbox detects a new service worker is installed and waiting,
 * this component shows a dismissable toast: "WorkRate has been updated — reload".
 * Tapping "Reload" calls skipWaiting on the new SW and reloads the page so the
 * user immediately gets the new build.
 *
 * Uses `virtual:pwa-register/react` — generated by vite-plugin-pwa at build time.
 * In development (no SW registered) this is a no-op.
 */
import { useEffect } from "react";
import { useRegisterSW } from "virtual:pwa-register/react";
import { useToast } from "@/hooks/use-toast";

export function PwaUpdatePrompt() {
  const { toast } = useToast();

  const {
    needRefresh: [needRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    // Called when a new SW is found. We show the toast instead of auto-reloading.
    onNeedRefresh() {
      // handled in useEffect below so we have stable toast reference
    },
    onOfflineReady() {
      // app is cached and ready to work offline (first install) — no UI needed
    },
    onRegisteredSW(swUrl, registration) {
      if (!registration) return;
      // Re-check for updates every 60 s while the app is open. This ensures that
      // a home-screen PWA that's been running for a while still picks up new builds.
      setInterval(() => registration.update(), 60_000);
    },
  });

  useEffect(() => {
    if (!needRefresh) return;
    const { dismiss } = toast({
      title: "WorkRate has been updated",
      description: "Reload to get the latest version.",
      duration: Infinity,
      action: (
        <button
          className="inline-flex h-8 shrink-0 items-center justify-center rounded-md border border-transparent bg-orange-600 px-3 text-sm font-medium text-white ring-offset-background transition-colors hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
          onClick={() => {
            dismiss();
            updateServiceWorker(true);
          }}
        >
          Reload
        </button>
      ),
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [needRefresh]);

  return null;
}
