// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/MemphisFurnitureDatingLandingPage-KHPiJK/App.tsx": () => import("../components/mockups/templates/MemphisFurnitureDatingLandingPage-KHPiJK/App.tsx"),
  "./components/mockups/workrate-dashboard/Earthy.tsx": () => import("../components/mockups/workrate-dashboard/Earthy.tsx"),
  "./components/mockups/workrate-dashboard/Refined.tsx": () => import("../components/mockups/workrate-dashboard/Refined.tsx"),
  "./components/mockups/workrate-dashboard/TopNavLayout.tsx": () => import("../components/mockups/workrate-dashboard/TopNavLayout.tsx")
};
